### ISSUE TITLE
Phive Support

### ISSUE THREAD

**Issue by sfaujour** [Aeliot-Tm/php-cs-fixer-baseline#3]
Thanks a lot for this project, it will help us a lot.
We are using PHPCsFixer with Phive, so we want also use this with Phive too. 
Currently i don't know the requirements to make it available for PHIVE, but it seems that a PHAR file is needed, within the project.

Would this be possible to implement?

**Comment by Aeliot-Tm** [comment]
Hi @sfaujour,

It would be nice! Thank you for suggestion!
I'll try to find time for this in 3 nearest weeks. Or well you free to contribute it :smiley:

**Comment by sfaujour** [comment]
@Aeliot-Tm Thank you and no pressure. I'll try to have a look, but with no guarantee and not within the next 2 weeks.

**Comment by Aeliot-Tm** [comment]
Hi @sfaujour,

I implemented support of PHAR. See release [v1.2.0](https://github.com/Aeliot-Tm/php-cs-fixer-baseline/releases/tag/v1.2.0)

**Comment by Aeliot-Tm** [comment]
Hi @sfaujour, 

Alias `php-cs-fixer-baseline` of this project was accepted and merged into database of phar.io.
https://github.com/phar-io/phar.io/pull/158
Just wait till it will be deployed.

Then you'll be able to call `phive install php-cs-fixer-baseline`.

See issue https://github.com/phar-io/phar.io/issues/157 for explanation.

**Comment by theseer** [comment]
You can tell phive to update the database file with `phive update-repository-list` - no need to wait ;)

**Comment by sfaujour** [comment]
@Aeliot-Tm Looks great and works as expected. Love it! ❤️
