### ISSUE TITLE
Missing Path for autoloader throws RuntimeException

### ISSUE THREAD

**Issue by sfaujour** [Aeliot-Tm/php-cs-fixer-baseline#4]
When installing the composer package, the autoloader can not be found, as the path you are trying to resolve for the autoload, has a additional depth of 2.

Adding another line within the $paths array, within `vendor/aeliot/php-cs-fixer-baseline/bin/pcsf-baseline` in my case, helped me out:

```
$paths = [
        __DIR__ . '/vendor/autoload.php',
        __DIR__ . '/../vendor/autoload.php',
        __DIR__ . '/../../vendor/autoload.php',
        __DIR__ . '/../../../../vendor/autoload.php',
    ];
```

**Comment by Aeliot-Tm** [comment]
Hi @sfaujour,

Version with fix of this issue released: v1.0.1
Could you try it?

**Comment by Aeliot-Tm** [comment]
Sorry for late answer

**Comment by sfaujour** [comment]
@Aeliot-Tm Hi and sorry, was on holidays :) I'll try it this week 🙂
