### ISSUE TITLE
PHIVE GPG Key Issue

### ISSUE THREAD

**Issue by sfaujour** [Aeliot-Tm/php-cs-fixer-baseline#45]
Since today we have issues installing the phive package, whilst the key on the keyserver can't be found.
Did you change something regarding to this project?

| Q                             | A               |
|-------------------------------|-----------------|
| PHP CS Fixer Baseline version | 2.0.0           |
| PHP version                   | 8.2.14           |
| Installation Method           | PHIVE |

#### Summary

Phive installation with trusted gpg key can't be installed

#### Current behavior

Phive Package with Signature can't be installed with the following command:

#### How to reproduce

`phive install --trust-gpg-keys 83F9945BC33EC39E9710206C8B4927076BA50A83`

#### Expected behavior

Package with the above command can be installed (or with a different gpg key if updated)

**Comment by Aeliot-Tm** [comment]
Hi @sfaujour,

Key was changed. Try to install latest version signed by new key `9D0DD6FCB92C84688B777DF59204DEE8CAE9C22C`?

FYI: you can use short fingerprint of key as value of argument  `--trust-gpg-keys`: `9204DEE8CAE9C22C`

--- 
P.S.
Check my script "phive-install" in composer.json. Maybe this approach to the managing of trusted keys would be useful for you.

**Comment by sfaujour** [comment]
@Aeliot-Tm Thank you! We've updated the key and it works.
